" Generated by vim-plug
" Thu Sep 25 11:38:43 2025
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['bitproto'].commit = 'b3c46748331effb8dd141968f656472c018ce142'
silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '99290b3ec1322070bcfb9e846450a46f6efa50f0'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['cppinsights.vim'].commit = '4cc9c5556566e40cf21008b7aeba95ec211d6bb7'
silent! let g:plugs['csharpls-extended-lsp.nvim'].commit = '50d7a1dc539d9e0f28106fc238b7bc108cb8af16'
silent! let g:plugs['diffview.nvim'].commit = '4516612fe98ff56ae0415a259ff6361a89419b0a'
silent! let g:plugs['fzf'].commit = '3ba82b6d87348b119f9a7fd168ad8a597a18b4b2'
silent! let g:plugs['fzf.vim'].commit = 'f06bd1e69b7e5c77dbdef40ca8d31292fc926d3c'
silent! let g:plugs['godbolt.nvim'].commit = 'ffb1b98087daa1e10087a3bf06c30291a17b1310'
silent! let g:plugs['indent-blankline.nvim'].commit = '9637670896b68805430e2f72cf5d16be5b97a22a'
silent! let g:plugs['lualine.nvim'].commit = 'f4f791f67e70d378a754d02da068231d2352e5bc'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['nightfox.nvim'].commit = 'ba47d4b4c5ec308718641ba7402c143836f35aa9'
silent! let g:plugs['none-ls-extras.nvim'].commit = '6557f20e631d2e9b2a9fd27a5c045d701a3a292c'
silent! let g:plugs['none-ls.nvim'].commit = 'a66b5b9ad8d6a3f3dd8c0677a80eb27412fa5056'
silent! let g:plugs['nvim-autopairs'].commit = '68f0e5c3dab23261a945272032ee6700af86227a'
silent! let g:plugs['nvim-cmp'].commit = '5a11682453ac6b13dbf32cd403da4ee9c07ef1c3'
silent! let g:plugs['nvim-lspconfig'].commit = 'fb733ac734249ccf293e5c8018981d4d8f59fa8f'
silent! let g:plugs['nvim-treesitter'].commit = '8bc635a25f581d42b0a0e5ba8870bd73244dcdea'
silent! let g:plugs['onedarkpro.nvim'].commit = 'b2712b3163f2b531cc26d1af07f49f683460e5a3'
silent! let g:plugs['outline.nvim'].commit = 'ae473fb51b7b6086de0876328c81a63f9c3ecfef'
silent! let g:plugs['papercolor-theme'].commit = '0cfe64ffb24c21a6101b5f994ca342a74c977aef'
silent! let g:plugs['papercolor-theme-slim'].commit = 'fbf849da9d6de87de626f865fb9988d2e595eeb5'
silent! let g:plugs['plenary.nvim'].commit = '857c5ac632080dba10aae49dba902ce3abf91b35'
silent! let g:plugs['sig-window-nvim'].commit = 'c1efe38484880877bb3ea4acfb8c7fd04fcc240d'
silent! let g:plugs['targets.vim'].commit = '6325416da8f89992b005db3e4517aaef0242602e'
silent! let g:plugs['vim-cppman'].commit = '1fe11060f5bfc72d20f2c928dd3c06a309db50fc'
silent! let g:plugs['vim-fugitive'].commit = '4a745ea72fa93bb15dd077109afbb3d1809383f2'
silent! let g:plugs['vim-macroeditor'].commit = '25fd58a712f58ed16ebe924c4f92c9999e455e95'
silent! let g:plugs['vim-signify'].commit = '8670143f9e12ed1cd3c9b2c54f345cdd9a4baac3'
silent! let g:plugs['vim-visual-multi'].commit = 'a6975e7c1ee157615bbc80fc25e4392f71c344d4'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'
silent! let g:plugs['winresizer'].commit = '9bd559a03ccec98a458e60c705547119eb5350f3'
silent! let g:plugs['zoomwintab.vim'].commit = '3b76f740534ecc4114bc8a207ecb0db77b2fb002'

PlugUpdate!

