" Generated by vim-plug
" Sat Jan 11 14:50:02 2025
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['cmp-buffer'].commit = '3022dbc9166796b644a841a02de8dd1cc1d311fa'
silent! let g:plugs['cmp-nvim-lsp'].commit = '99290b3ec1322070bcfb9e846450a46f6efa50f0'
silent! let g:plugs['cmp-vsnip'].commit = '989a8a73c44e926199bfd05fa7a516d51f2d2752'
silent! let g:plugs['cppinsights.vim'].commit = '4cc9c5556566e40cf21008b7aeba95ec211d6bb7'
silent! let g:plugs['csharpls-extended-lsp.nvim'].commit = 'bedd4fbf74ebe644f2c3723327972f468fd98e4e'
silent! let g:plugs['diffview.nvim'].commit = '4516612fe98ff56ae0415a259ff6361a89419b0a'
silent! let g:plugs['fzf'].commit = '9030b67e4f80256f91023a01c3fb2bdab060d717'
silent! let g:plugs['fzf.vim'].commit = '556f45e79ae5e3970054fee4c4373472604a1b4e'
silent! let g:plugs['godbolt.nvim'].commit = 'ffb1b98087daa1e10087a3bf06c30291a17b1310'
silent! let g:plugs['indent-blankline.nvim'].commit = '9637670896b68805430e2f72cf5d16be5b97a22a'
silent! let g:plugs['lualine.nvim'].commit = '2a5bae925481f999263d6f5ed8361baef8df4f83'
silent! let g:plugs['nerdtree'].commit = '9b465acb2745beb988eff3c1e4aa75f349738230'
silent! let g:plugs['nerdtree-git-plugin'].commit = 'e1fe727127a813095854a5b063c15e955a77eafb'
silent! let g:plugs['none-ls-extras.nvim'].commit = '6557f20e631d2e9b2a9fd27a5c045d701a3a292c'
silent! let g:plugs['none-ls.nvim'].commit = '0143bb5f117f76863cf0c24bcf0724d3137f04d2'
silent! let g:plugs['nvim-autopairs'].commit = 'd2f791ceeb26d04d87aa54343bc94e8ad8d7be1c'
silent! let g:plugs['nvim-cmp'].commit = '8c82d0bd31299dbff7f8e780f5e06d2283de9678'
silent! let g:plugs['nvim-lspconfig'].commit = '88157521e890fe7fdf18bee22438875edd6300a6'
silent! let g:plugs['nvim-treesitter'].commit = '306dd6e9dc806db1d79568d26e1c9b6c98b95fbc'
silent! let g:plugs['onedarkpro.nvim'].commit = '515d3299832d9e4a46296c8e5bc9a3eb539b5044'
silent! let g:plugs['papercolor-theme'].commit = '0cfe64ffb24c21a6101b5f994ca342a74c977aef'
silent! let g:plugs['papercolor-theme-slim'].commit = '9be11f4e02ad71535ea131e70f914d62fa58ddda'
silent! let g:plugs['plenary.nvim'].commit = '2d9b06177a975543726ce5c73fca176cedbffe9d'
silent! let g:plugs['sig-window-nvim'].commit = '606e9dbd1f80646c8d2d1b4384872ec718ddc48a'
silent! let g:plugs['smear-cursor.nvim'].commit = '005b50b891d662bdd3160dc2a143939066b5cc17'
silent! let g:plugs['targets.vim'].commit = '6325416da8f89992b005db3e4517aaef0242602e'
silent! let g:plugs['vim-cppman'].commit = '1fe11060f5bfc72d20f2c928dd3c06a309db50fc'
silent! let g:plugs['vim-fugitive'].commit = '174230d6a7f2df94705a7ffd8d5413e27ec10a80'
silent! let g:plugs['vim-macroeditor'].commit = '25fd58a712f58ed16ebe924c4f92c9999e455e95'
silent! let g:plugs['vim-signify'].commit = '8670143f9e12ed1cd3c9b2c54f345cdd9a4baac3'
silent! let g:plugs['vim-visual-multi'].commit = 'a6975e7c1ee157615bbc80fc25e4392f71c344d4'
silent! let g:plugs['vim-vsnip'].commit = '02a8e79295c9733434aab4e0e2b8c4b7cea9f3a9'
silent! let g:plugs['winresizer'].commit = '9bd559a03ccec98a458e60c705547119eb5350f3'
silent! let g:plugs['zoomwintab.vim'].commit = '3b76f740534ecc4114bc8a207ecb0db77b2fb002'

PlugUpdate!

